---
- name: automatic first installation
  hosts: freshint
  tasks:
    - name: Check that user exists
      shell: "grep jenkins1 /etc/passwd"
      ignore_errors: yes
      become: yes
      register: userexist
      
    - name: user status output
      debug:
        msg: "{{userexist.stdout}}"
   
    - name: user add
      shell: useradd jenkins1
      become: yes
      when: userexist.stdout | length < 1

    - name: editing sudoers
      become: yes
      become_user: root
      lineinfile:
        path: /etc/sudoers
        line: "jenkins1 ALL=(ALL) NOPASSWD: ALL"
        state: present
      notify:
      - restart ssh

    - name: Pause for 15 seconds to restart ssh
      pause:
         seconds: 1

    - name: Ansible apt to install multiple packages
      apt:
        name: "{{ item }}"
        update_cache: yes
        state: present
      with_items:
         - 'nginx'
         - 'npm'
         - 'ansible'
         - 'git'
      become: yes
      register: aptout 
      
    - debug:
         msg: "{{ aptout }}"

  handlers:
      - name: restart ssh
        become: yes
        become_user: root
        service: 
         name: ssh 
         state: restarted
